### ISSUE TITLE
rebar3 error

### ISSUE THREAD

**Issue by matheuscamarques** [novaframework/nova#116]
Reading rebar3 configuration failed. Check your file (and if it does not exist - create it). The file is:
escript: exception error: bad argument
  in function  io:format/3
     called as io:format(<0.62.0>,"~s~n","/")

**Comment by matheuscamarques** [comment]
Reading rebar3 configuration failed. Check your file (and if it does not exist - create it). The file is:
escript: exception error: bad argument
  in function  io:format/3
     called as io:format(<0.62.0>,"~s~n","/")
sanonichan@dkt-lyn-0001:~$ rebar3 new nova my_first_nova
template not found.
sanonichan@dkt-lyn-0001:~$ rebar3
Rebar3 is a tool for working with Erlang projects.

  Set the environment variable DEBUG=1 for detailed output.

Usage: rebar3 [-h] [-v] [<task>]

  -h, --help     Print this help.
  -v, --version  Show version information.
  <task>         Task to run.

Several tasks are available:

as                Higher order provider for running multiple tasks in a sequence as a certain profiles.
clean             Remove compiled beam files from apps.
compile           Compile apps .app.src and .erl files.
cover             Perform coverage analysis.
ct                Run Common Tests.
deps              List dependencies
dialyzer          Run the Dialyzer analyzer on the project.
do                Higher order provider for running multiple tasks in a sequence.
edoc              Generate documentation using edoc.
escriptize        Generate escript archive.
eunit             Run EUnit Tests.
get-deps          Fetch dependencies.
help              Display a list of tasks or help for a given task or subtask.
new               Create new project from templates.
path              Print paths to build dirs in current profile.
pkgs              List information for a package.
release           Build release of project.
relup             Create relup of releases.
report            Provide a crash report to be sent to the rebar3 issues page.
shell             Run shell with project apps and deps in path.
tar               Tar archive of release built of project.
tree              Print dependency tree.
unlock            Unlock dependencies.
update            Update package index.
upgrade           Upgrade dependencies.
version           Print version for rebar and current Erlang.
xref              Run cross reference analysis.

local <task>:
  install        Extract libs from rebar3 escript along with a run script.
  upgrade        Download latest rebar3 escript and extract.

plugins <task>:
  list           List local and global plugins for this project
  upgrade        Upgrade plugins

Run 'rebar3 help <TASK>' for details.

**Comment by Taure** [comment]
I think the issue is that you are missing the rebar.config file. 

~/.config/rebar3/rebar.config

In the rebar.config file it should be a line with `{plugins, []}.` .

After this try to run the installation script again.

**Comment by matheuscamarques** [comment]
that worked @Taure 
, but need to create the rebar3 folder in ~/.config

**Comment by Taure** [comment]
I have opened this issue in rebar3_nova so we can solve it.

https://github.com/novaframework/rebar3_nova/issues/12
