### ISSUE TITLE
nova_router render status page and lookup fails we call module that does not exist

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#117]
`2021-11-04T19:26:04.868209+01:00 error: [nova_handler] Controller crashed (error, undef), Stacktrace: [{nova_controller,status_code,[#{body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"cache-control">> => <<"no-cache">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"session_id=s1EvOn/1DuLA/XVHsA6BicDVszRPjlsYinkLPYIRgCw=; server=Cowboy/Nova">>,<<"host">> => <<"localhost:8080">>,<<"pragma">> => <<"no-cache">>,<<"referer">> => <<"http://localhost:8080/">>,<<"sec-ch-ua">> => <<"\"Chromium\";v=\"94\", \" Not A;Brand\";v=\"99\", \"Opera GX\";v=\"80\"">>,<<"sec-ch-ua-mobile">> => <<"?0">>,<<"sec-ch-ua-platform">> => <<"\"Windows\"">>,<<"sec-fetch-dest">> => <<"image">>,<<"sec-fetch-mode">> => <<"no-cors">>,<<"sec-fetch-site">> => <<"same-origin">>,<<"user-agent">> => <<"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 OPR/80.0.4170.86">>},host => <<"localhost">>,method => <<"GET">>,path => <<"/favicon.ico">>,peer => {{127,0,0,1},48562},pid => <0.2025.0>,port => 8080,qs => <<>>,ref => nova_listener,resp_cookies => #{<<"server">> => [<<"server">>,<<"=">>,<<"Cowboy/Nova">>,<<"; Version=1">>,[]]},scheme => <<"http">>,sock => {{127,0,0,1},8080},streamid => 2,version => 'HTTP/1.1'}],[]},{nova_handler,execute,2,[{file,"/home/daniel/project/nova_project/my_first_app/_build/default/lib/nova/src/nova_handler.erl"},{line,40}]},{cowboy_stream_h,execute,3,[{file,"/home/daniel/project/nova_project/my_first_app/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,306}]},{cowboy_stream_h,request_process,3,[{file,"/home/daniel/project/nova_project/my_first_app/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,295}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]`

We try to call on a module nova_controller that does not exist anymore.

https://github.com/novaframework/nova/blob/master/src/nova_router.erl#L299

**Comment by Taure** [comment]
This only appears if we have routing as a module instead of a priv routing as an erlang file.

https://github.com/Taure/my_first_app this repo use routing as a module in src.

**Comment by burbas** [comment]
Yeah, I know why this is occuring and the error message you get is spot on :). We miss the nova_controller which I've forgotten about. Will fix that.
