### ISSUE TITLE
nova_handler gives both ok value and a not found value

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#118]
From a newly templated nova application when going to localhost:8080 I can see that the nova_handler logs two entries:
```

2021-11-04T20:05:05.603971+01:00 info: [nova_handler] Called handler: {ok,[{message,"Hello world!"}]}
2021-11-04T20:05:05.655254+01:00 info: [nova_handler] Called handler: {ok,#{message => "We could not find the page you were looking for",status => "Could not find the page you were looking for",title => "404 Not found"},#{view => nova_error}}
```
This is when routing file is in priv as my_other_app.routes.erl

**Comment by burbas** [comment]
I can not replicate this issue. Are you sure this is still relevant to Nova?

**Comment by Taure** [comment]
Will have a check later. But it was simple to replicate from a new templated nova app.

But we might have solved it in earlier PR.

**Comment by Taure** [comment]
I can still reproduce it.

Steps:
1. `rebar3 new nova my_app`
2. Change rebar.config to nova master branch
3. `rebar3 shell`
4. Open browser and go to localhost:8080

**Comment by burbas** [comment]
That's because you are requesting with the browser (Which tries to fetch favicon). So if you instead of step 4 do a curl to localhost:
`curl localhost:8080`

That should give you one entry in the logs.

**Comment by Taure** [comment]
I look at network in browser and that gives me 200 ok on all request.

Could it be an option that is asked before regular request taht we get an 404 on?

**Comment by Taure** [comment]
Correct it is the favicon issue.
