### ISSUE TITLE
Create test suite for the framework itself

### ISSUE THREAD

**Issue by burbas** [novaframework/nova#12]
This is a really important issue since it allows us to ensure that a release is working before tagging it. My suggestion is that we introduce unit-tests for early catches and have a dockerized environment which we can define a workflow in - eg. create a nova application, start it and make a couple of curl calls to ensure it works.

**Comment by Taure** [comment]
Maybe use this https://github.com/tsloughter/docker_compose_cth and start Nova in a docker that we run tests against?

**Comment by burbas** [comment]
Creating cause of stale issue
