### ISSUE TITLE
Path with ending / thinks it is empty binding

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#128]
If we have a routing file like:

```erlang
#{prefix => "",
   security => false,
   routes => [{"/mypath", {module, function}, #{methods => [get]}},
                     {"/mypath/:mypathid", {module, function2}, #{methods => [get]}}]}
```

Then we do a request to `/mypath/` lookup will think we are getting the second one with binding when we should really get the segment with no binding.

**Comment by burbas** [comment]
This is a bug in the `routing_tree` application. Will see if I can update that to handle the case with trailing `/`

**Comment by Taure** [comment]
Should we link an issue to that repo?

**Comment by burbas** [comment]
Should be fixed with this PR in `routing_tree`: https://github.com/novaframework/routing_tree/pull/6

**Comment by burbas** [comment]
PR merged
