### ISSUE TITLE
Setting for turning off html view at error

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#142]
I think it would be great if it would be possible to turn HTML error return back from request if something fails. To have a setting for it. It is nice if you are working with views and see if something goes wrong.

But if you only use endpoints it is not a smooth feeling when you get back HTML on a curl or in a test.

**Comment by Taure** [comment]
I am thinking if we maybe want three values here?

None - it returns only status code
Html - web page
Json - stacktrace in an error

**Comment by burbas** [comment]
Wouldn’t it make sense to only have `{display_error, true/false}` and check the accept-header instead. If it’s `application/json` we return JSON and otherwise we’ll return HTML.
