### ISSUE TITLE
We should either have production or prod, development or dev

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#153]
In nova_sup we have mixed terminology.

```erlang
    case Environment of
        production ->
            ?NOTICE("Starting nova in production mode...");
        dev ->
            ?NOTICE("Starting nova in developer mode...")
    end,
```

It is looking for production but in rebar3_nova we set production sys.config as prod.

**Comment by burbas** [comment]
This is now a non-issue. I removed that section in https://github.com/novaframework/nova/pull/156. We are not really using this anywhere right now. The only place where we actually use this is when calling the router.
