### ISSUE TITLE
Distributed session management

### ISSUE THREAD

**Issue by burbas** [novaframework/nova#16]

**Comment by burbas** [comment]
Implement a new backend that uses mnesia.

**Comment by burbas** [comment]
Perhaps we should look to alternatives for mnesia? In Erlang 23 epmd is optional and if someone would like to use docker and its service lookup instead of epmd it might be a problem? I'm not 100% sure how it works. An alternative would be using redis or something similar to achieve this.

**Comment by mcesaro** [comment]
Might be better to keep options open, i.e. make it a configurable external service? There are a few mnesia alternatives for DSM, 100% erlang.

**Comment by burbas** [comment]
> Might be better to keep options open, i.e. make it a configurable external service? There are a few mnesia alternatives for DSM, 100% erlang.

I totally agree with you. We should not limit ourselves to just one service but have this configurable through an interface. So I think this story is more about designing such an interface.

**Comment by burbas** [comment]
Think we can close this for now. It's been here since 2019 :P. We can re-create it if there's a need for this.
