### ISSUE TITLE
Add a guideline for how to install Erlang and Rebar3

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#167]
Erlang and Rebar3 is something that is used in Nova.

We should add a section pointing to [Adopting Erlang](https://adoptingerlang.org/docs/development/setup/).

In the directory guides we keep markdown files with guides and documentation about Nova.

**Comment by burbas** [comment]
This was added in https://github.com/novaframework/nova/commit/fd1771bcc93a60d390e4083ff977c7188db7ee8e

Closing the PR
