### ISSUE TITLE
[FEATURE REQ.] Support Erlang 20+

### ISSUE THREAD

**Issue by burbas** [novaframework/nova#179]
**Is your feature request related to a problem? Please describe.**
Want to support older systems

**Describe the solution you'd like**
There's two applications that makes this harder: thaos and logger. The solution would be to ifdef these and replace them with Erlang 20+ compatible options if running an older version.

**Additional context**
I think we can ifdef most of the items that clashes with older Erlang versions. Think we could even support older systems than 20 (We need maps so before Erlang 17 is hard).

**Comment by Taure** [comment]
Is this still valid? If I remember correct Cowboy doesn't support otp 20.

**Comment by burbas** [comment]
We are dropping support for this. Perhaps a good idea is to support current_major_version - 3 (If current version is 25 then we should support erl 22 and above)

**Comment by Taure** [comment]
I agree to this. I think rebar3 that we use have kind of the same terms. 

Then we decide we will suppport current major version - 3.
