### ISSUE TITLE
[TOPIC]  How to cluster an application

### ISSUE THREAD

**Issue by matheuscamarques** [novaframework/nova#184]
Hi guys, today I'm studying Erlang more and more and I want to start a project with the Nova framework but my question is how can I scale this application with Nova.
How can I add new clusters to this application?

**Comment by Taure** [comment]
Today we don't have an excellent way to scale it inside the framework. We are working on channels, the same as phoenix has, that use distributed Erlang. In this way, you could connect many different nodes to send messages between using the channels. https://github.com/novaframework/nova/pull/176

If you want to scale with the Nova version of today, I would use a message queue system like Rabbitmq and have consumers on each Nova node handle them.

And then, as usual, have load balancers in front to send requests to each node to handle more requests and so on.

If you want to get into distributed erlang, you could write that code inside your nova application that connects with your other nova applications.

@burbas, do you have anything to add to this?
