### ISSUE TITLE
[BUG] Referencing to a non-existent template should result in a 404

### ISSUE THREAD

**Issue by burbas** [novaframework/nova#203]
**Describe the bug**
If we define a controller that returns the following:
```
{ok, [], #{view => no_existing_template}}.
```
Nova will crash with an exception thrown that the template can't be found.

**Expected behavior**
A generated 404 page should be returned

**Comment by Taure** [comment]
Could we add that it throws a warning or something?

So we an say like you are trying to point to a view that we couldn't find?

**Comment by burbas** [comment]
> Could we add that it throws a warning or something?
> 
> So we an say like you are trying to point to a view that we couldn't find?

We're already doing that but we need to send a rendered page back to the user. Think we might need to check the logic around rendering and validation in the whole pipeline.
