### ISSUE TITLE
[BUG] Views not rendered when using multi-app

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#218]
**Describe the bug**
When adding other nova app to your app views stop working. It shows a blank page.

**If this is a complex bug**
[Nova Login](https://github.com/novaframework/nova_login) 
**Expected behavior**
When going to `http://localhost:8080/login` we should see a github login button. But we see a blank page.

**Comment by burbas** [comment]
Think this might be something with your setup :). I had to change the `dev_sys.config.src` so the `CLIENTID` and `CLIENTSECRET` was encapsulated with `"`. But then it worked as expected. Can you confirm this?

**Comment by burbas** [comment]
@Taure If you have any comments regarding this please add it - otherwise I'll mark this as resolved and close it :)

**Comment by Taure** [comment]
I resolve it for now and open it if it happens again.
