### ISSUE TITLE
SSL private keyfile option missing and is not included in the cert.pem from Lets Encrypt Certificates

### ISSUE THREAD

**Issue by etxemag75** [novaframework/nova#292]
Lets Encrypt generates these files (from README):
`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.
`chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
`cert.pem`     : will break many server configurations, and should not be used
                 without reading further documentation (see link below).

Nova config.src:
ca_cert => "fullchain.pem"
cert => "cert.pem"

Todays Nova SSL implemementation only takes "ca_cert" and "cert" options, which does not work unless you manually merge privkey.pem into cert.pem as a temporary 90 days workaround 

**Expected behavior**
In nova_sup.erl, please include a new optional config for "privkey"

**Comment by Taure** [comment]
Thank you. Will have a look at this.
