### ISSUE TITLE
[BUG] request_correlation_header not normalized

### ISSUE THREAD

**Issue by kivra-kenand** [novaframework/nova#295]
**Describe the bug**
Setting request_correlation_header with uppercase characters causes it to never match

**If this is a complex bug**
sys.config:
```
...
 #{request_correlation_header => <<"custom-X-id">>
...
```

SUITE:
```
Headers = #{headers => #{"content-type" => "application/json", <<"custom-X-id">> => <<"foo">>}},
#{status := {201, _}, headers := Res} = jhn_shttpc:post(["http://custom_url"], <<"[]">>, Headers),
?assertEqual(<<"foo">>, maps:get(<<"x-correlation-id">>, Res)).
```
The code [here](https://github.com/novaframework/nova/blob/087de83b7383543c64910717f18fe5badb5541ce/src/plugins/nova_correlation_plugin.erl#L76) will never match `custom-X-id` as it has been normalized to `custom-x-id`.

**Expected behavior**
request_correlation_header should be normalized before matching. So that `request_correlation_header => <<"cUsToM-X-iD">>` would match `CuStOm-x-Id` in the headers.

**Desktop (please complete the following information):**
 - OS: N/A
 - Erlang version: 27
 - Nova version: v0.10.2

**Comment by burbas** [comment]
Thanks for reporting the issue. It's been fixed with the pull request mentioned above.
