### ISSUE TITLE
Nova Secure Routing needs improvements and fixing at least redirect

### ISSUE THREAD

**Issue by etxemag75** [novaframework/nova#298]
1) Update Doc to better explain the return values of the callback security function like security => fun security_controller:do_security/1, but after reading the code (nova_security_handler.erl), it is similar to Controller Handlers, so would be good if you could clarify better in doc.

2) Redirecting a user to a certain login page is important in many web page applications, but nothing happens when returning {redirect, "/my/other/path}. when testing under http. 

3) Update doc to better explain what this function should do other than validating login credentials that could be maintained between different web pages, is this function supposed to store session-based (cookies) or use token-based authentication, because I don't see authentication information in the Cowboy Req  beyond the page after the login, also it is not possible to pass on updated Req to set a new cookie: 

    		Req1 = cowboy_req:set_resp_cookie(<<"session_auth">>, "abc123xyz", #{max_age => 3600, path => "/", http_only => true, secure => false}, Req),
			{true, Req1#{authed => true, username => "abcdef"}};

**Comment by burbas** [comment]
Thanks @etxemag75 for your comments regarding this. The documentation have been a point we were hoping to improve a lot during 2025 but I know it's a little comfort right now. I will try to write some better documentation for securing routes with a simple example of how to use it this weekend.

The redirection is a bit strange. You are calling it correctly and it should result in a 302 IIRC but will see if I can build a simple test-case for this.

Again - thanks for the input and hopefully we can adress all of these rather soon - hopefully by the end of this weekend.

**Comment by etxemag75** [comment]
Thank you for your quick response on this issue

Just to clarify a little bit more, other than the Doc issues:

'auth_data' from the security function, comes in Req for the subsequent view served (i.e. the page after a successful login), but is not maintained on pages or web requests (like clicking buttons etc) beyond that. (Other Nova data in the Req like 'plugins' etc is maintained)

**Comment by burbas** [comment]
You are correct. The Req-object is only per-request. So if you have a token-based security setup your security-handler will check incoming requests, validate the token and (optionally) inject that info into auth_data. 

I guess you refer to the fact that `auth_data` is not present in all requests, which is correct. It's only if you decide to output something from your security handler that it will be present.

**Comment by burbas** [comment]
Your 3rd point is actually a very valid one which we have not addressed. It's currently not possible to do this, but will take a look at it and see if I can come up with a solution that works for most use cases :-)

**Comment by burbas** [comment]
Will close this issue now and keep the one you created separately regarding the redirections. If you feel that this issue should still be open please create another one.

**Comment by burbas** [comment]
And thanks for reporting this to us :)
