### ISSUE TITLE
Routing and Module:Function

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#50]
Today we can specify routing like this:

```Erlang
{"/v1/user", { my_controller, create_user}, #{methods => [post]}},
{"/v1/user/:userid", {my_controller, manage_user}, #{methods => [put, get, delete]}}
```

Each endpoint can only handle one function. It would be nice to be able to point different methods to different functions.

Example:
```Erlang
{"/v1/user", post, { my_controller, create_user}, ...},
{"/v1/user/:userid", get, { my_user_controller, get_user} ... },
{"/v1/user/:userid", put, { my_user_controller, change_user}, ... },
{"/v1/user/:userid", delete, { my_controller, remove_user}, ... }
```
In this way we can get explicit functions from routing and methods. And it is also easy to see what endpoint points against Module:Function.

**Comment by burbas** [comment]
It would be cool to build a tree out of the routes and that way be able to handle what you are saying. Then we can have a much better pre-handling of routes imho.
