### ISSUE TITLE
Add opentelematey

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#57]
We should add so we use opentelematry to collect data. That can be used by others to view data and logs.

**Comment by burbas** [comment]
This should be a bit easier now with both pre- and post handlers. I think we could achieve this, but I'm not 100% convinced it should be part of the core. What do you think @Taure? My initial feeling is that it could be a plugin that you pull in case you want support for opentelematey

**Comment by Taure** [comment]
After looking into it I think this could be turned into a nova_ot_plugin that you add if you want opentelemetry stuff.
