### ISSUE TITLE
Erlydtl gives warning because of get_stacktrace()

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#6]
Erlydtl is using functions that will be depricated.

We should raise this to Erlydtl but also manage it until they have a fix.

**Comment by burbas** [comment]
I've made a pull request for this from our fork. Let's see if they accept this today, otherwise we might want to point to our fork of erlydtl instead.

**Comment by Taure** [comment]
I guess we need to see how we can handle warning in erlydtl in the future.

**Comment by Taure** [comment]
Is this done with the new commit for erlydtl?

**Comment by burbas** [comment]
erlydtl have accepted the MR we made so we can close this.
