### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#65]
Is this something we should handle in Nova or should we create a plugin for it so users can decide by them self how it should be used in their applications?

Example is that OPTIONS should not have auth on it and return data on what methods is allowed and headers. Is it possible to solve today, but it need some boilerplate code in all controllers to work.

**Comment by Taure** [comment]
https://github.com/novaframework/nova/commit/dc7bac80af8680aa910fe8312354c09938c718b3

Something like this, in this case it will skip the controller if method is a options.

**Comment by burbas** [comment]
I think this could be a plugin and included with the default plugins in core.

**Comment by Taure** [comment]
Ok so we make like a nova_plugin_cors that returns {ok, Req, State} if it is not an OPTION else it return {stop, Req, State}?

Maybe do a cowboy req reply in the plugin. Should we have plugins in a directory?

Also before we have the priority in place of plugins this need to go first?

**Comment by burbas** [comment]
Sounds good. It’s not necessary that this is run first even though it would be best(?). But let’s run with what we have for now.

**Comment by Taure** [comment]
I agree, we could use pre to handle this so controllers doesn't need to handle options.

**Comment by Taure** [comment]
This is solved in 0.6.0 that we can handle CORS with a plugin.
