### ISSUE TITLE
Refactor nova_router

### ISSUE THREAD

**Issue by burbas** [novaframework/nova#85]
Today the router is structured as a gen-server with lots of handle_cast-cases. This works okay, but gets a bit complex. One suggestion is to refactor the router and move most of the parsing-actions to separate methods instead and use the gen-server as a orcestrator for routes - handling the communications with cowboy and provide an API that one clients can query to modify/remove/add routes.

Also include the suggestions from #50 when refactoring this

**Comment by Taure** [comment]
One idea is maybe to change the file consult handling of routes. If we are doing a refactoring. If other beam languages want to use Nova and not write routes as an Erlang map. But a map representation for the beam language they use.

Not sure if we want that change. Was more a thought after doing the lfe part where they compile lfe route file to an Erlang route file.

**Comment by burbas** [comment]
It's not a bad idea. Just thinking if this creates unnecessary complexity, but we should be just fine if we have it as an option that defaults to file:consult.
