### ISSUE TITLE
Install script

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#91]
New install script should:
Idea is to have a script that install the plugins and check if some of the pre-reqs are installed.
- [x] check if rebar3 is installed
- [x]  if rebar3 is not installed ask if latest version should be downloaded
- [ ]  check if erlang is installed
- [ ]  If erlang is not installed give a warning
- [x]  Add rebar3_nova to plugins in ~/.cache/rebar3/rebar.config

**Comment by burbas** [comment]
More or less done except the erlang-stuff since I wrote the script as an escript 😁
