### ISSUE TITLE
static routing is not working in 0.7.1

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#94]
With new routing in place static routing is not working.

https://github.com/Taure/trylfe

this repo have static routing that returns 404 instead of correct html file. Old version it works.

**Comment by Taure** [comment]
It looks like statics field is missing in the route map so the routes will not be applied.

**Comment by burbas** [comment]
Will take a look at it. But probably a problem with route transformation.

**Comment by burbas** [comment]
Fixed in tagged release v0.7.2
