### ISSUE TITLE
Make sure we can use Erlang 24

### ISSUE THREAD

**Issue by Taure** [novaframework/nova#99]
We have some dependencies that need to solve otp 24 for functions that will be deprecated. We should look into this before 24 is released.

**Comment by Taure** [comment]
Fixed in latest jhn_stdlib. Updated to latest version.

**Comment by Taure** [comment]
https://github.com/ninenines/ranch/issues/314

Ranch has otp 24 issues so this will also affect Cowboy.

**Comment by burbas** [comment]
Resolved with 0df89e678787f41cb8421ec2d35cd8cfb1cb8286
